Fixed compiling issue for Autumn
revoltchat/autumn pull request #30
Opened 2023-09-01 05:24 UTC by toastxc

## Please make sure to check the following tasks before opening and submitting a PR

* [x] I understand and have followed the [contribution guide](https://github.com/revoltchat/revolt/discussions/282)
* [x] I have tested my changes locally and they are working as intended
* [x] These changes do not have any notable side effects on other Revolt projects

2023-09-01 05:30 UTC, toastxc commented
The latest compiliation test on Github compiled `tokio-cron-scheduler` to version `v0.2.3`, however locally compiling `*` is resolved to `v0.9.4`.

2023-12-01 21:16 UTC, insertish requested changes

2023-12-01 21:16 UTC, insertish commented on src/routes/upload.rs
> +        let content_type = field.content_disposition();
Not sure why this got affected?

2024-07-31 10:50 UTC, insertish commented
Stale PR

2024-07-31 10:50 UTC, closed without merging